// Read-mostly Prisma client for medico's existing tables (users, caregivers,
// bookings, health_reports, emergency_contacts, ...). Generated by
// `prisma db pull` against prisma/medico-readonly/schema.prisma — NEVER run
// `prisma migrate` or `prisma db push` with that schema.
//
// This client is used to:
//   - look up a medico `users` row by phone for Ayuxa Connect family login
//   - look up a medico `caregivers` row by phone for Ayuxa Buddy login
//   - read booking/health-report data for display
// It must not be used to alter medico's schema, and app-level writes
// against these tables should stay narrow and explicit (see
// src/services/medico.repository.js for the sanctioned read/write list).
const { PrismaClient } = require('../../node_modules/.prisma/medico-readonly-client');

const medicoPrisma = new PrismaClient({
    log: process.env.NODE_ENV === 'development' ? ['warn', 'error'] : ['error'],
    datasources: { db: { url: process.env.DATABASE_URL } },
});

process.on('SIGINT', async () => { await medicoPrisma.$disconnect(); process.exit(0); });
process.on('SIGTERM', async () => { await medicoPrisma.$disconnect(); process.exit(0); });

module.exports = medicoPrisma;
